[phases.setup]
nixPkgs = [
    "php84",
    "php84Packages.composer",
    "php84Extensions.pdo_pgsql",
    "php84Extensions.pdo_mysql",
    "php84Extensions.mbstring",
    "php84Extensions.iconv",
    "php84Extensions.tokenizer",
    "php84Extensions.bcmath",
    "php84Extensions.fileinfo",
    "php84Extensions.curl",
    "php84Extensions.zip",
    "php84Extensions.dom",
    "php84Extensions.gd",
    "nodejs",
    "postgresql_17"
]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install && npm run build",
    "mkdir -p storage/framework/sessions storage/framework/views storage/framework/cache storage/logs bootstrap/cache storage/app/temp-restores",
    "chmod -R 775 storage bootstrap/cache",
    "php artisan view:clear",
    "php artisan config:cache"
]

[variables]
    # Eliminamos PHP_INI_SCAN_DIR para no bloquear las extensiones de Nix

[start]
    cmd = "php artisan migrate --force && php -d upload_max_filesize=100M -d post_max_size=100M -d memory_limit=512M artisan serve --host=0.0.0.0 --port=$PORT"
